const {
    NODE_ENV,
    NEXT_PUBLIC_APP_HOST,
    AUTH_SECRET,
    AUTH_FACEBOOK_ID,
    AUTH_FACEBOOK_SECRET,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    RESEND_API_KEY,
    CLOUDINARY_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
} = process.env;

export {
    AUTH_FACEBOOK_ID,
    AUTH_FACEBOOK_SECRET,
    AUTH_SECRET,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_NAME,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    NEXT_PUBLIC_APP_HOST,
    NODE_ENV,
    RESEND_API_KEY,
};
